---
  hosts: all
  become: yes
  tasks:
  - name: update packages and install tomcat7
    apt:
      name: tomcat7
      state: present
      update_cache: yes
    notify: 
    - restart tomcat7
  handlers: 
  - name: restart tomcat7
    service:
      name: tomcat7
      enabled: yes
      state: restarted